name: Weekly python Script

on:
  schedule:
    - cron: '* * * * *' # Runs every Sunday at 00:00 (midnight)
  workflow_dispatch:

jobs:
  run-script:
    environment:
      name: ig
    runs-on: ubuntu-latest
    
    steps:
    - run: ls
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'
        cache: 'pip'
    - name: Update requirements
    - run: pip install -r requirements.txt
    - name: Run script
      env:
        IG_USERNAME: ${{ secrets.IG_USERNAME }}
        IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
    - run: python instascrap.py
        
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Update from weekly script" || echo "No changes to commit"
        git push origin HEAD
